BASE_PATH_DOCUMENTOS = r"D:\data_eleccia\01_inscripcion_lista\documentos"

# Constantes para los tipos de documentos
DDJJ_CONSENTIMIENTO = "DDJJ_DE_CONSENTIMIENTO_DE_PARTICIPACIÓN.pdf"
DDJJ_DEUDA_REPARACION = "DDJJ_DE_NO_TENER_DEUDA_DE_REPARACIÓN_CIVIL.pdf"
DDJJ_LICENCIA = "DDJJ_DE_SOLICITUD_DE_LICENCIA.pdf"
DDJJ_RENUNCIA = "DDJJ_DE_RENUNCIA_AL_CARGO.pdf"
DDJJ_EXTRANJERO = "DDJJ_CONSTANCIA_DE_INSCRIPCIÓN_PARA_EXTRANJERO.pdf"
DDJJ_DOMICILIO_MULTIPLE = "DDJJ_ACREDITACIÓN_DE_DOMICILIO_MÚLTIPLE.pdf"
DJJ_PLAZO = "DECLARACIÓN_JURADA_DE_HOJA_DE_VIDA.pdf"
COMPROBANTE_PAGO = "COMPROBANTE_DE_PAGO.pdf"
DJJ_HV = "DECLARACIÓN_JURADA_DE_HOJA_DE_VIDA.pdf"
OTROS="OTROS.PDF"


# Mapeo entre nombres de archivo y códigos de requisitos en la base de datos
MAPEO_REQUISITOS = {
    DDJJ_CONSENTIMIENTO: "DDJJ_CONSENTIMIENTO",
    DDJJ_DEUDA_REPARACION: "DDJJ_NO_DEUDA",
    DDJJ_LICENCIA: "DDJJ_DE_LICENCIA",
    DDJJ_RENUNCIA: "DDJJ_DE_RENUNCIA",
    DDJJ_EXTRANJERO: "DDJJ_INSCRIPCION_EXTRANJERO",
    DDJJ_DOMICILIO_MULTIPLE: "DDJJ_DOMICILIO_MULTIPLE",
    DJJ_PLAZO: "DDJJ_PLAZO",
    COMPROBANTE_PAGO: "COMPROBANTE_DE_PAGO",
    DJJ_HV: "DDJJ_HV"
}

