-- Tabla de Estados (Maestro de Estados)
CREATE TABLE ELECCIA.ELECCIA_TRF_ESTADOS (
    ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_ESTADO VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION CLOB,
    ES_ACTIVO NUMBER(1) DEFAULT 1,
    TIPO_ESTADO VARCHAR2(50) NOT NULL -- Para categorizar: SISTEMA, EXPEDIENTE, REQUISITO, etc.
);

-- Tabla de Tipos de Expediente (Maestro)
CREATE TABLE ELECCIA.ELECCIA_TRF_TIPOS_EXPEDIENTES (
    ID_TIPO_EXPEDIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_TIPO_EXPEDIENTE VARCHAR2(50) NOT NULL UNIQUE,   
    DESCRIPCION CLOB,
    ID_ESTADO NUMBER,
    CREADO_POR VARCHAR2(255),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_TIPO_EXPEDIENTE_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Materias (Maestro)
CREATE TABLE ELECCIA.ELECCIA_TRF_MATERIAS (
    ID_MATERIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_MATERIA VARCHAR2(50) NOT NULL UNIQUE,    
    DESCRIPCION CLOB,
    ID_ESTADO NUMBER,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_MATERIA_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Requisitos (Maestro)
CREATE TABLE ELECCIA.ELECCIA_TRF_REQUISITOS (
    ID_REQUISITO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO_REQUISITO VARCHAR2(50) NOT NULL UNIQUE,   
    DESCRIPCION CLOB,
    ID_ESTADO NUMBER,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_REQUISITO_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Configuración de Requisitos por Tipo de Expediente y Materia
CREATE TABLE ELECCIA.ELECCIA_TBL_REQUISITOS_TIPO_EXP_MAT (
    ID_CONFIGURACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_TIPO_EXPEDIENTE NUMBER NOT NULL,
    ID_MATERIA NUMBER NOT NULL,
    ID_REQUISITO NUMBER NOT NULL,
    ES_OBLIGATORIO NUMBER(1) DEFAULT 1,
    PRIORIDAD NUMBER,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_TBL_REQ_TIPO_EXP FOREIGN KEY (ID_TIPO_EXPEDIENTE) 
        REFERENCES ELECCIA.ELECCIA_TRF_TIPOS_EXPEDIENTES(ID_TIPO_EXPEDIENTE),
    CONSTRAINT FK_TBL_REQ_MATERIA FOREIGN KEY (ID_MATERIA) 
        REFERENCES ELECCIA.ELECCIA_TRF_MATERIAS(ID_MATERIA),
    CONSTRAINT FK_TBL_REQ_REQUISITO FOREIGN KEY (ID_REQUISITO) 
        REFERENCES ELECCIA.ELECCIA_TRF_REQUISITOS(ID_REQUISITO)
);

-- Tabla de Expedientes
CREATE TABLE ELECCIA.ELECCIA_TBL_EXPEDIENTES (
    ID_EXPEDIENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_EXPEDIENTE VARCHAR2(100) NOT NULL UNIQUE,
    NOMBRE_EXPEDIENTE VARCHAR2(255) NOT NULL,
    DESCRIPCION CLOB,
    ID_TIPO_EXPEDIENTE NUMBER NOT NULL,
    ID_MATERIA NUMBER NOT NULL,
    ID_ESTADO NUMBER NOT NULL, -- PENDIENTE, EN_PROCESO, COMPLETADO
    USUARIO_ASIGNADO VARCHAR2(255),
    CREADO_POR VARCHAR2(255),
    CREADO_EN TIMESTAMP DEFAULT SYSTIMESTAMP,
    MODIFICADO_POR VARCHAR2(255),
    MODIFICADO_EN TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_EXPEDIENTE_TIPO_EXP FOREIGN KEY (ID_TIPO_EXPEDIENTE) 
        REFERENCES ELECCIA.ELECCIA_TRF_TIPOS_EXPEDIENTES(ID_TIPO_EXPEDIENTE),
    CONSTRAINT FK_EXPEDIENTE_MATERIA FOREIGN KEY (ID_MATERIA) 
        REFERENCES ELECCIA.ELECCIA_TRF_MATERIAS(ID_MATERIA),
    CONSTRAINT FK_EXPEDIENTE_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Candidatos
CREATE TABLE ELECCIA.ELECCIA_TBL_CANDIDATOS (
    ID_CANDIDATO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DNI VARCHAR2(8) NOT NULL UNIQUE,
    NOMBRES VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    DIRECCION VARCHAR2(255) NOT NULL,
    UBIGEO VARCHAR2(6) NOT NULL,
    PUESTO_POSTULA VARCHAR2(255) NOT NULL,
    NUMERO_LISTA NUMBER,
    ID_ESTADO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_CANDIDATO_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Educación de Candidatos
CREATE TABLE ELECCIA.ELECCIA_TBL_EDUCACION_CANDIDATOS (
    ID_EDUCACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANDIDATO NUMBER NOT NULL,
    NIVEL_EDUCATIVO VARCHAR2(100) NOT NULL,
    CENTRO_EDUCATIVO VARCHAR2(255) NOT NULL,
    ESPECIALIDAD VARCHAR2(255),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    TITULO_OBTENIDO VARCHAR2(255),
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_EDUCACION_CANDIDATO FOREIGN KEY (ID_CANDIDATO) 
        REFERENCES ELECCIA.ELECCIA_TBL_CANDIDATOS(ID_CANDIDATO)
);

-- Tabla de Bienes de Candidatos
CREATE TABLE ELECCIA.ELECCIA_TBL_BIENES_CANDIDATOS (
    ID_BIEN NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANDIDATO NUMBER NOT NULL,
    TIPO_BIEN VARCHAR2(100) NOT NULL,
    DESCRIPCION VARCHAR2(255) NOT NULL,
    VALOR DECIMAL(15,2),
    FECHA_ADQUISICION DATE,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_BIENES_CANDIDATO FOREIGN KEY (ID_CANDIDATO) 
        REFERENCES ELECCIA.ELECCIA_TBL_CANDIDATOS(ID_CANDIDATO)
);

-- Tabla de Historial Laboral de Candidatos
CREATE TABLE ELECCIA.ELECCIA_TBL_HISTORIAL_LABORAL (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CANDIDATO NUMBER NOT NULL,
    EMPRESA VARCHAR2(255) NOT NULL,
    CARGO VARCHAR2(255) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    FUNCIONES CLOB,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_HISTORIAL_CANDIDATO FOREIGN KEY (ID_CANDIDATO) 
        REFERENCES ELECCIA.ELECCIA_TBL_CANDIDATOS(ID_CANDIDATO)
);

-- Tabla de Archivos Adjuntos
CREATE TABLE ELECCIA.ELECCIA_TBL_ARCHIVOS_ADJUNTOS (
    ID_ARCHIVO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR2(255) NOT NULL,
    RUTA_ARCHIVO VARCHAR2(500) NOT NULL,
    TIPO_ARCHIVO VARCHAR2(50) NOT NULL, -- PDF, DOC, IMG, etc.
    TAMANIO_ARCHIVO NUMBER, -- en bytes
    ID_ESTADO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_ARCHIVO_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);

-- Tabla de Relación de Archivos con Entidades
CREATE TABLE ELECCIA.ELECCIA_TBL_ARCHIVOS_ENTIDADES (
    ID_ARCHIVO_ENTIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ARCHIVO NUMBER NOT NULL,
    TIPO_ENTIDAD VARCHAR2(50) NOT NULL, -- REQUISITO, EDUCACION, BIEN, HISTORIAL_LABORAL
    ID_ENTIDAD NUMBER NOT NULL, -- ID de la entidad relacionada
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    CONSTRAINT FK_ARCHIVO_ENTIDAD_ARCHIVO FOREIGN KEY (ID_ARCHIVO) 
        REFERENCES ELECCIA.ELECCIA_TBL_ARCHIVOS_ADJUNTOS(ID_ARCHIVO)
);

-- Tabla de Estados de Requisitos por Expediente
CREATE TABLE ELECCIA.ELECCIA_TBL_ESTADO_REQUISITOS_EXP (
    ID_ESTADO_REQUISITO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EXPEDIENTE NUMBER NOT NULL,
    ID_CONFIGURACION NUMBER NOT NULL,
    ID_CANDIDATO NUMBER NULL,
    TIPO_REQUISITO VARCHAR2(50) NOT NULL, -- GENERAL, CANDIDATO
    ID_ESTADO_VALIDACION NUMBER NOT NULL, -- CUMPLE, NO_CUMPLE, PENDIENTE
    VALIDACION_ANTERIOR VARCHAR2(50),
    OBSERVACIONES CLOB,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_ESTADO_REQ_EXP FOREIGN KEY (ID_EXPEDIENTE) 
        REFERENCES ELECCIA.ELECCIA_TBL_EXPEDIENTES(ID_EXPEDIENTE),
    CONSTRAINT FK_ESTADO_REQ_CONFIGURACION FOREIGN KEY (ID_CONFIGURACION) 
        REFERENCES ELECCIA.ELECCIA_TBL_REQUISITOS_TIPO_EXP_MAT(ID_CONFIGURACION),
    CONSTRAINT FK_ESTADO_REQ_CANDIDATO FOREIGN KEY (ID_CANDIDATO) 
        REFERENCES ELECCIA.ELECCIA_TBL_CANDIDATOS(ID_CANDIDATO),
    CONSTRAINT FK_ESTADO_REQ_VALIDACION FOREIGN KEY (ID_ESTADO_VALIDACION) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO),
    CONSTRAINT CHK_TIPO_REQUISITO CHECK (TIPO_REQUISITO IN ('GENERAL', 'CANDIDATO')),
    CONSTRAINT CHK_TIPO_REQUISITO_CANDIDATO CHECK (
        (TIPO_REQUISITO = 'GENERAL' AND ID_CANDIDATO IS NULL) OR
        (TIPO_REQUISITO = 'CANDIDATO' AND ID_CANDIDATO IS NOT NULL)
    )
);

-- Tabla de Resoluciones
CREATE TABLE ELECCIA.ELECCIA_TBL_RESOLUCIONES (
    ID_RESOLUCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_EXPEDIENTE NUMBER NOT NULL,
    CODIGO_RESOLUCION VARCHAR2(100) NOT NULL UNIQUE,
    TIPO_RESOLUCION VARCHAR2(255),
    DESCRIPCION_RESOLUCION CLOB,
    MOTIVO_RESOLUCION CLOB,
    ID_ESTADO NUMBER NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREADO_POR VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    CONSTRAINT FK_RESOLUCION_EXPEDIENTE FOREIGN KEY (ID_EXPEDIENTE) 
        REFERENCES ELECCIA.ELECCIA_TBL_EXPEDIENTES(ID_EXPEDIENTE),
    CONSTRAINT FK_RESOLUCION_ESTADO FOREIGN KEY (ID_ESTADO) 
        REFERENCES ELECCIA.ELECCIA_TRF_ESTADOS(ID_ESTADO)
);